### ISSUE TITLE
Access to state.set

### ISSUE THREAD

**Issue by dunnock** [grommet/react-formify#1]
Amazing lib, thanks @alansouzati !

Would be great if we can get access to state.set. I want to preload values to the form based on the selection list, though do not want to manage own component state. If I can get access to state.set solution would be quite simple:

```
function setBeta(state: *) {
  state.set('plan._id', 'beta')
  state.set('plan.name', 'Beta')
  state.set('plan.maxMachines', '5')
  state.set('plan.maxSnapshots', '5')
  state.set('plan.maxStorage', String(100*1024*1024*1024))
}
...
  <Button secondary accent type='button' label='Beta' onClick={()=>setBeta(state)}/>
```

**Comment by alansouzati** [comment]
Good question. It seems weird that an uncontrolled component will allow a `set` function.

Any reason for not using `defaultValue` in form?

```javascript
const betaPlan = {
  _id: 'beta',
  name: 'Beta',
  maxMachines: 5,
  maxSnapshots: 5,
  maxStorage: String(100*1024*1024*1024),
};

export default class SelectPlanForm extends Component {
  state = {
    plan: undefined,
  }
  selectBeta = () => this.setState({ plan: betaPlan })
  render() {
     const { plan } = this.state;
     return (
         <div>
           <Form defaultValue={{ plan }}>
              ...
           </Form>
           <Button secondary accent type='button' label='Use Beta' onClick={this.selectBeta}/>
         </div>
     );
  }
}
```

**Comment by dunnock** [comment]
The reason is I wanted to get rid of using not pure components in my code as much as I can...

**Comment by dunnock** [comment]
Yea, so far I am using class with setState and `defaultValue`... but would be good if all the state management stays in `react-formify` unless it breaks your design vision. Thanks

**Comment by alansouzati** [comment]
I see you point. Let me think about it. I'm myself not sure if allowing `set` for an `uncontrolled` component is wrong. Let me get back to you soon.

**Comment by alansouzati** [comment]
Yeah, after researching a little your request makes total sense. Let me work on that and release a new version with support for this.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/react-formify/commit/bfa48d59abef09026d3420e908b62f85f0979250.

v0.3.0 released with support for that.
